import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import path from 'node:path';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outdir = 'dist';

/**
 * Copy the static plugin assets next to the bundle so `dist/` is a complete,
 * loadable plugin folder (Obsidian needs main.js, manifest.json and styles.css
 * together). Runs after every (re)build, including in watch mode.
 */
const copyAssets = {
	name: 'copy-assets',
	setup(build) {
		build.onEnd(() => {
			fs.mkdirSync(outdir, { recursive: true });
			for (const file of ['manifest.json', 'styles.css']) {
				if (fs.existsSync(file)) fs.copyFileSync(file, path.join(outdir, file));
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outdir, 'main.js'),
	minify: prod,
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
